name: Build and Deploy to S3

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Navigate to repository directory
        run: cd real-estate-management  # Adjust this path if needed

      - name: Navigate to frontend directory
        run: cd Frontend  # Adjust this path if needed

      - name: Install dependencies
        run: npm install

      - name: Install Ionic CLI
        run: npm install -g @ionic/cli

      - name: Run Ionic Serve
        run: |
          ionic serve --no-open
